version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:12.16.1
      environment:
        TZ: Asia/Tokyo
  working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout

  deploy-s3:
    <<: *defaults
    steps:
      - run:
          name: 'deploy to s3'
          command: |
            sudo apt-get -y -qq install awscli
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/repo s3://${S3_BUCKET_NAME}
            fi

workflows:
  deploy:
    jobs:
      - setup
      - deploy-s3:
          requires:
            - setup
