version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:12.16.1
      environment:
        TZ: Asia/Tokyo
  working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - run:
          name: 'check pr number'
          command: echo ${CIRCLE_PULL_REQUEST}
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  deploy-s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'awscli install'
          command: sudo apt-get -y -qq install awscli
      - run:
          name: 'nuxt build'
          command: 'yarn build'
      - run:
          name: 'deploy to s3'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ls .
              echo "deploy to S3"
              aws s3 sync ~/repo/dist s3://${S3_BUCKET_NAME} --delete --exclude ".gitkeep" --exclude ".nojekyll" --exclude "*.map"
            fi

workflows:
  deploy:
    jobs:
      - setup
      # - deploy-s3:
      #     requires:
      #       - setup
