version: 2.1
default: &default
  docker:
    - image: circleci/node:12.16.1
      environment:
        TZ: Asia/Tokyo
  working_directory: ~/repo

jobs:
  setup:
    <<: *default
    steps:
      - checkout

  deploy-s3:
    <<: *default
    steps:
      - run:
        name: 'deploy to s3'
        command: |
          sudo apt-get -y -qq install awscli
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            aws s3 sync ~/repo s3://${S3_BUCKET_NAME} --delete
           fi

workflows:
  deploy:
    jobs:
      - setup
      - deploy-s3:
        requires:
          - setup
