version: 2.1
default: &default
  working_directory: ~/repo

jobs:
  setup:
    - checkout

  deploy-s3:
    <<: *default
      - run: 
          command: |
            sudo apt-get -y -qq install awscli
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/repo s3://${S3_BUCKET_NAME} --delete
            fi

workflows:
  deploy:
    jobs:
      - setup
      - deploy-s3
        requires:
          - setup