version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

defaults: &defaults
  docker:
    - image: circleci/node:12.16.1
      environment:
        TZ: Asia/Tokyo
  working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  deploy-s3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'awscli install'
          command: sudo apt-get -y -qq install awscli
      - run:
          name: 'set pr number'
          command: |
            if [[ $CIRCLE_PULL_REQUEST =~ ([0-9]+)$ ]]; then
              echo "export PR_NUMBER=${BASH_REMATCH[1]}" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: 'nuxt build'
          command: 'yarn build'
      - aws-s3/sync:
          arguments: '--delete --exclude ".gitkeep" --exclude ".nojekyll" --exclude "*.map"'
          from: ~/repo/dist
          to: 's3://${S3_BUCKET_NAME}/${PR_NUMBER}'

workflows:
  deploy:
    jobs:
      - setup
      - deploy-s3:
          requires:
            - setup
          filters:
            branches:
              ignore: master
